# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Apartamento',
                'verbose_name_plural': 'Apartamentos',
            },
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Condominio')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Condominio',
                'verbose_name_plural': 'Condominios',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='sobrenome')),
                ('apartamento', models.CharField(max_length=20, verbose_name='moradores.Apartamento')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Modificado em')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moradores.Condominio', verbose_name='Condominio')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.AddField(
            model_name='apartamento',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moradores.Condominio', verbose_name='Condominio'),
        ),
    ]
