# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Condominio'),
        ),
    ]
