# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='apartamento',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='moradores.Apartamento'),
        ),
    ]
