# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['name'], 'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='nome',
            new_name='name',
        ),
    ]
