# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moradores', '0002_auto_20171022_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condominio',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='morador',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='condominio',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='slug',
        ),
    ]
